# Generated by Django 6.0.4 on 2026-04-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_investedproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('icon_name', models.CharField(help_text='Lucide icon name (e.g., Building, MapPin, Leaf, Navigation)', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='investedproject',
            name='tags',
        ),
    ]
