# Generated by Django 6.0.4 on 2026-04-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_portfoliostat_remove_investedproject_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortfolioStat',
        ),
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name_plural': 'Inquiries'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.AddField(
            model_name='investedproject',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
