# Generated by Django 6.0.4 on 2026-04-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_portfoliostat_alter_inquiry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
