# Generated by Django 6.0.4 on 2026-04-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_careerapplication_updated_at_contact_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price_currency',
            field=models.CharField(choices=[('INR', 'Rupees (₹)'), ('USD', 'Dollars ($)')], default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='size_unit',
            field=models.CharField(choices=[('SQFT', 'Sq. Ft.'), ('SQM', 'Sq. M.'), ('ACRE', 'Acres')], default='SQFT', max_length=20),
        ),
    ]
