# Generated by Django 6.0.4 on 2026-05-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_property_price_currency_property_size_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investedproject',
            name='image',
            field=models.ImageField(default='placeholder.png', upload_to='invested_projects/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investedproject',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
