"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Use python-dotenv if available to load .env file
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-7^c8fa=0n(^%m5#z^#gr36)=%ke1hjp18gedo@8ivaz10i2*j$')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [host.strip() for host in os.environ.get('ALLOWED_HOSTS', '*').split(',')]
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in os.environ.get('CSRF_TRUSTED_ORIGINS', 'http://localhost:3000,http://127.0.0.1:3000').split(',')]


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'unfold.contrib.inlines',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'corsheaders',
    'storages',
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Static files storage is set inside the STORAGES dict below when S3 is
# enabled; this line keeps the whitenoise default for non-S3 environments.
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ---------------------------------------------------------------------------
# Media / File Storage — S3 + CloudFront
# ---------------------------------------------------------------------------
# When AWS credentials are configured, files are uploaded directly to S3
# and all image URLs are rewritten through CloudFront (CDN gateway).
# If credentials are absent the app falls back to local media storage so
# development still works without AWS.
# ---------------------------------------------------------------------------

AWS_ACCESS_KEY_ID       = os.environ.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY   = os.environ.get('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.environ.get('S3_BUCKET_NAME', 'kci-media')
AWS_S3_REGION_NAME      = os.environ.get('AWS_REGION', 'us-east-2')
CLOUDFRONT_BASE_URL     = os.environ.get('CLOUDFRONT_BASE_URL', '')

if AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY and AWS_STORAGE_BUCKET_NAME:
    # ── S3 bucket settings ────────────────────────────────────────────────
    # file_overwrite=True: skip the extra HEAD request that checks for
    # existing keys — we use UUID-prefixed keys so collisions won't happen.
    AWS_S3_FILE_OVERWRITE        = True
    AWS_DEFAULT_ACL              = None           # bucket policy controls access
    AWS_S3_OBJECT_PARAMETERS     = {'CacheControl': 'max-age=86400'}
    AWS_QUERYSTRING_AUTH         = False          # public reads via CloudFront

    # ── Multipart / transfer config ────────────────────────────────────────
    # Use parallel multipart upload for files > 8 MB to speed up large files.
    import boto3.s3.transfer as _s3t
    AWS_S3_TRANSFER_CONFIG = _s3t.TransferConfig(
        multipart_threshold=8 * 1024 * 1024,   # 8 MB
        max_concurrency=10,
        multipart_chunksize=8 * 1024 * 1024,
        use_threads=True,
    )

    # ── Presigned-URL upload settings ────────────────────────────────────
    # Controls how long a generated presigned PUT URL stays valid (seconds).
    AWS_PRESIGNED_EXPIRY = int(os.environ.get('AWS_PRESIGNED_EXPIRY', 900))  # 15 min

    # ── Storage backends ──────────────────────────────────────────────────
    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
            'OPTIONS': {
                'bucket_name':    AWS_STORAGE_BUCKET_NAME,
                'region_name':    AWS_S3_REGION_NAME,
                'access_key':     AWS_ACCESS_KEY_ID,
                'secret_key':     AWS_SECRET_ACCESS_KEY,
                'file_overwrite': True,
                'default_acl':    None,
            },
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }

    # ── Media URLs served via CloudFront ──────────────────────────────────
    if CLOUDFRONT_BASE_URL:
        # All ImageField / FileField .url values will be rewritten to:
        #   https://<cloudfront-domain>/<s3-key>
        MEDIA_URL = CLOUDFRONT_BASE_URL.rstrip('/') + '/'
    else:
        # Fall back to direct S3 URL if CloudFront isn't configured
        MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/'

    MEDIA_ROOT = ''  # not used when storing in S3

else:
    # ── Local fallback (development without AWS) ──────────────────────────
    MEDIA_URL  = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'

# Unfold settings
from django.templatetags.static import static
from django.urls import reverse_lazy


UNFOLD = {
    "SITE_TITLE": "Kanji Capital Admin",
    "SITE_HEADER": "",
    "SITE_URL": "/",
    "SITE_SYMBOL": "account_balance",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "STYLES": [
        lambda request: static("css/admin_custom.css"),
    ],
    "SITE_LOGO": {
        "light": lambda request: static("images/logo.jpg"),
        "dark": lambda request: static("images/logo.jpg"),
    },
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "sizes": "32x32",
            "type": "image/jpeg",
            "href": lambda request: static("images/logo.jpg"),
        },
    ],
    "COLORS": {
        "primary": {
            "50": "250 249 248",
            "100": "245 241 238",
            "200": "235 227 218",
            "300": "223 209 194",
            "400": "194 169 144",
            "500": "176 148 120",
            "600": "158 126 95",
            "700": "135 106 80",
            "800": "110 87 67",
            "900": "89 71 56",
            "950": "46 36 29",
        },
    },
    "LOGIN": {
        "redirect_after": "/",
    },
    "TABS": [
        {
            "models": ["api.property"],
            "items": [
                {
                    "title": "All Properties",
                    "link": reverse_lazy("admin:api_property_changelist"),
                },
            ],
        },
        {
            "models": ["api.careerapplication"],
            "items": [
                {
                    "title": "All Applications",
                    "link": reverse_lazy("admin:api_careerapplication_changelist"),
                },
            ],
        },
    ],
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Main",
                "separator": True,
                "items": [
                    {
                        "title": "Dashboard",
                        "icon": "speed",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },
            {
                "title": "Website Content",
                "separator": True,
                "items": [
                    {
                        "title": "Site Statistics",
                        "icon": "analytics",
                        "link": reverse_lazy("admin:api_sitestatistic_changelist"),
                    },
                    {
                        "title": "Tenants",
                        "icon": "group",
                        "link": reverse_lazy("admin:api_tenant_changelist"),
                    },
                ],
            },
            {
                "title": "Real Estate",
                "separator": True,
                "items": [
                    {
                        "title": "Properties",
                        "icon": "apartment",
                        "link": reverse_lazy("admin:api_property_changelist"),
                        "badge": "core.badges.property_count",
                    },
                    {
                        "title": "Invested Projects",
                        "icon": "trending_up",
                        "link": reverse_lazy("admin:api_investedproject_changelist"),
                        "badge": "core.badges.invested_project_count",
                    },
                ],
            },
            {
                "title": "Customer Relations",
                "separator": True,
                "items": [
                    {
                        "title": "Contacts",
                        "icon": "person_search",
                        "link": reverse_lazy("admin:api_contact_changelist"),
                        "badge": "core.badges.contact_count",
                    },
                    {
                        "title": "Inquiries",
                        "icon": "quiz",
                        "link": reverse_lazy("admin:api_inquiry_changelist"),
                        "badge": "core.badges.inquiry_count",
                    },
                    {
                        "title": "Newsletters",
                        "icon": "newspaper",
                        "link": reverse_lazy("admin:api_newsletter_changelist"),
                        "badge": "core.badges.newsletter_count",
                    },
                ],
            },
            {
                "title": "Recruitment",
                "separator": True,
                "items": [
                    {
                        "title": "Career Applications",
                        "icon": "work_history",
                        "link": reverse_lazy("admin:api_careerapplication_changelist"),
                        "badge": "core.badges.career_application_count",
                    },
                ],
            },
            {
                "title": "Access Control",
                "separator": True,
                "items": [
                    {
                        "title": "Users",
                        "icon": "manage_accounts",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                        "badge": "core.badges.user_count",
                    },
                    {
                        "title": "Groups",
                        "icon": "shield_person",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
        ],
    },
}
# Email Notification Settings
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@kanjicapitalinvestments.com')
NOTIFICATION_EMAIL = os.environ.get('NOTIFICATION_EMAIL', 'anil@kanjicapitalinvestments.com')
